# Generated by Django 3.1.5 on 2021-01-09 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_poststatistic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostStatistic',
        ),
    ]
